/**
 * Bundle src/web/widget.src.ts -> src/web/widget.mjs as a single self-contained
 * ESM module. The host serves widget.mjs raw and the browser dynamically
 * import()s it, so it must resolve with zero bare imports: socket.io-client is
 * inlined; React stays EXTERNAL (the host injects it via props.React).
 */
import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const common = {
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  legalComments: 'none',
  banner: { js: '/* @cemoody/pi-crust-ext-browser web module — generated by scripts/build-web.mjs. Do not edit. */' },
};

// Sidebar activity widget (React external — host injects it).
await build({
  ...common,
  entryPoints: [path.join(root, 'src', 'web', 'widget.src.ts')],
  outfile: path.join(root, 'src', 'web', 'widget.mjs'),
  external: ['react', 'react-dom'],
});
console.log('built src/web/widget.mjs');

// Tier-B inline-card client (no React; loaded inside the sandboxed iframe).
await build({
  ...common,
  entryPoints: [path.join(root, 'src', 'web', 'live-card.src.ts')],
  outfile: path.join(root, 'src', 'web', 'live-card.js'),
});
console.log('built src/web/live-card.js');
